### ISSUE TITLE
Every plugins "State" starts at "Stop"

### ISSUE THREAD

**Issue by Ie0h** [Owain94/OpenOSRS-external-plugins#135]
Posting this here since Discord seems to be gone and invites do not work but regardless of which plugin I run, it never starts and the state gets stuck on "Stop".

I start at the required location each plugin specifies, but never changes from "Stop"

https://gyazo.com/36275c1e8b91ad89c2c1dc3e0d13a47c
https://gyazo.com/81d7f0f05920a00cac9f07206ffa82ab

**Comment by Ie0h** [comment]
Also happens to Mahogany Homes

**Comment by Owain94** [comment]
OpenOSRS can't be used at this moment.

**Comment by Ie0h** [comment]
Is it not compatible with unethical?
