### ISSUE TITLE
World Hopper Currently Broken

### ISSUE THREAD

**Issue by Campfirecrucifix** [Owain94/OpenOSRS-external-plugins#63]
If someone logs in and you are in a world that is not checked as a hoppable world in your settings (US, UK, etc.) the client freezes and the only way to fix it is to restart the client. 
Ex: You are on a US world and you have hop to US worlds disabled in settings the client will freeze when it tries to auto hop.

If someone logs in to (US for example) world that you are on and you do have (US worlds) as checked a hoppable in the settings then it will keep trying to hop to the same world that you are currently on.
Ex: You are on a US world with US worlds enabled in settings it will keep trying to hop to the same world that you are on.

**Comment by xKylee** [comment]
@Campfirecrucifix do you hang any errors in your logs?

**Comment by Owain94** [comment]
Just tested this, seems to be working on the latest release (pushed just now)
